package agencia.entity;
// Generated 27/05/2011 17:03:33 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int idCliente;
     private String nombre;
     private String apellido;
     private String usuario;
     private String pass;
     private Date fechaNacimiento;
     private String nacionalidad;

    public Cliente() {
    }

	
    public Cliente(int idCliente) {
        this.idCliente = idCliente;
    }
    public Cliente(int idCliente, String nombre, String apellido, String usuario, String pass, Date fechaNaciemiento, String nacionalidad) {
       this.idCliente = idCliente;
       this.nombre = nombre;
       this.apellido = apellido;
       this.usuario = usuario;
       this.pass = pass;
       this.fechaNacimiento = fechaNaciemiento;
       this.nacionalidad = nacionalidad;
    }
   
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public Date getFechaNaciemiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNaciemiento(Date fechaNaciemiento) {
        this.fechaNacimiento = fechaNaciemiento;
    }
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }




}


