package agencia.entity;
// Generated 10/06/2011 10:34:34 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Proveedor generated by hbm2java
 */
@Entity
@Table(name="Proveedor"
    ,catalog="Agencia_de_Turismo_DB"
)
public class Proveedor  implements java.io.Serializable {


     private Integer idProveedor;
     private String razonSocial;
     private String usuario;
     private String pass;
     private Set<Servicio> servicios = new HashSet<Servicio>(0);

    public Proveedor() {
    }

    public Proveedor(String razonSocial, String usuario, String pass, Set<Servicio> servicios) {
       this.razonSocial = razonSocial;
       this.usuario = usuario;
       this.pass = pass;
       this.servicios = servicios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idProveedor", unique=true, nullable=false)
    public Integer getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(Integer idProveedor) {
        this.idProveedor = idProveedor;
    }
    
    @Column(name="razonSocial", length=45)
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    
    @Column(name="usuario", length=45)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    
    @Column(name="pass", length=45)
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="proveedor")
    public Set<Servicio> getServicios() {
        return this.servicios;
    }
    
    public void setServicios(Set<Servicio> servicios) {
        this.servicios = servicios;
    }




}


