package agencia.entity;
// Generated 14/06/2011 00:41:34 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private Integer idFactura;
     private Cliente cliente;
     private String fechaEmicion;
     private Set<LineaFactura> lineaFacturas = new HashSet<LineaFactura>(0);

    public Factura() {
    }

	
    public Factura(Cliente cliente) {
        this.cliente = cliente;
    }
    public Factura(Cliente cliente, String fechaEmicion, Set<LineaFactura> lineaFacturas) {
       this.cliente = cliente;
       this.fechaEmicion = fechaEmicion;
       this.lineaFacturas = lineaFacturas;
    }
   
    public Integer getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(Integer idFactura) {
        this.idFactura = idFactura;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public String getFechaEmicion() {
        return this.fechaEmicion;
    }
    
    public void setFechaEmicion(String fechaEmicion) {
        this.fechaEmicion = fechaEmicion;
    }
    public Set<LineaFactura> getLineaFacturas() {
        return this.lineaFacturas;
    }
    
    public void setLineaFacturas(Set<LineaFactura> lineaFacturas) {
        this.lineaFacturas = lineaFacturas;
    }




}


