package agencia.entity;
// Generated 10/06/2011 10:34:34 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Factura generated by hbm2java
 */
@Entity
@Table(name="Factura"
    ,catalog="Agencia_de_Turismo_DB"
)
public class Factura  implements java.io.Serializable {


     private Integer idFactura;
     private Cliente cliente;
     private String fechaEmicion;
     private Set<LineaFactura> lineaFacturas = new HashSet<LineaFactura>(0);

    public Factura() {
    }

	
    public Factura(Cliente cliente) {
        this.cliente = cliente;
    }
    public Factura(Cliente cliente, String fechaEmicion, Set<LineaFactura> lineaFacturas) {
       this.cliente = cliente;
       this.fechaEmicion = fechaEmicion;
       this.lineaFacturas = lineaFacturas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idFactura", unique=true, nullable=false)
    public Integer getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(Integer idFactura) {
        this.idFactura = idFactura;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Cliente_idCliente", nullable=false)
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    
    @Column(name="fechaEmicion", length=45)
    public String getFechaEmicion() {
        return this.fechaEmicion;
    }
    
    public void setFechaEmicion(String fechaEmicion) {
        this.fechaEmicion = fechaEmicion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="factura")
    public Set<LineaFactura> getLineaFacturas() {
        return this.lineaFacturas;
    }
    
    public void setLineaFacturas(Set<LineaFactura> lineaFacturas) {
        this.lineaFacturas = lineaFacturas;
    }




}


