package agencia.entity;
// Generated 10/06/2011 10:34:34 by Hibernate Tools 3.2.1.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LineaFactura generated by hbm2java
 */
@Entity
@Table(name="LineaFactura"
    ,catalog="Agencia_de_Turismo_DB"
)
public class LineaFactura  implements java.io.Serializable {


     private LineaFacturaId id;
     private Servicio servicio;
     private Factura factura;
     private String precio;

    public LineaFactura() {
    }

	
    public LineaFactura(LineaFacturaId id, Servicio servicio, Factura factura) {
        this.id = id;
        this.servicio = servicio;
        this.factura = factura;
    }
    public LineaFactura(LineaFacturaId id, Servicio servicio, Factura factura, String precio) {
       this.id = id;
       this.servicio = servicio;
       this.factura = factura;
       this.precio = precio;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idLineaFactura", column=@Column(name="idLineaFactura", nullable=false) ), 
        @AttributeOverride(name="facturaIdFactura", column=@Column(name="Factura_idFactura", nullable=false) ) } )
    public LineaFacturaId getId() {
        return this.id;
    }
    
    public void setId(LineaFacturaId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="Servicio_idServicio", referencedColumnName="idServicio", nullable=false), 
        @JoinColumn(name="Servicio_Proveedor_idProveedor", referencedColumnName="Proveedor_idProveedor", nullable=false) } )
    public Servicio getServicio() {
        return this.servicio;
    }
    
    public void setServicio(Servicio servicio) {
        this.servicio = servicio;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Factura_idFactura", nullable=false, insertable=false, updatable=false)
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    
    @Column(name="precio", length=45)
    public String getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(String precio) {
        this.precio = precio;
    }




}


