package agencia.entity;
// Generated 14/06/2011 00:41:34 by Hibernate Tools 3.2.1.GA



/**
 * LineaFactura generated by hbm2java
 */
public class LineaFactura  implements java.io.Serializable {


     private LineaFacturaId id;
     private Servicio servicio;
     private Factura factura;
     private String precio;

    public LineaFactura() {
    }

	
    public LineaFactura(LineaFacturaId id, Servicio servicio, Factura factura) {
        this.id = id;
        this.servicio = servicio;
        this.factura = factura;
    }
    public LineaFactura(LineaFacturaId id, Servicio servicio, Factura factura, String precio) {
       this.id = id;
       this.servicio = servicio;
       this.factura = factura;
       this.precio = precio;
    }
   
    public LineaFacturaId getId() {
        return this.id;
    }
    
    public void setId(LineaFacturaId id) {
        this.id = id;
    }
    public Servicio getServicio() {
        return this.servicio;
    }
    
    public void setServicio(Servicio servicio) {
        this.servicio = servicio;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public String getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(String precio) {
        this.precio = precio;
    }




}


