package agencia.entity;
// Generated 27/05/2011 17:03:33 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private int idProveedor;
     private String razonSocial;
     private String usuairo;
     private String pass;
     private Set<Servicio> servicios = new HashSet<Servicio>(0);

    public Proveedor() {
    }

	
    public Proveedor(int idProveedor) {
        this.idProveedor = idProveedor;
    }
    public Proveedor(int idProveedor, String razonSocial, String usuairo, String pass, Set<Servicio> servicios) {
       this.idProveedor = idProveedor;
       this.razonSocial = razonSocial;
       this.usuairo = usuairo;
       this.pass = pass;
       this.servicios = servicios;
    }
   
    public int getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(int idProveedor) {
        this.idProveedor = idProveedor;
    }
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    public String getUsuairo() {
        return this.usuairo;
    }
    
    public void setUsuairo(String usuairo) {
        this.usuairo = usuairo;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public Set<Servicio> getServicios() {
        return this.servicios;
    }
    
    public void setServicios(Set<Servicio> servicios) {
        this.servicios = servicios;
    }




}


