package agencia.entity;
// Generated 10/06/2011 10:34:34 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Servicio generated by hbm2java
 */
@Entity
@Table(name="Servicio"
    ,catalog="Agencia_de_Turismo_DB"
)
public class Servicio  implements java.io.Serializable {


     private ServicioId id;
     private Proveedor proveedor;
     private String nombre;
     private Float costo;
     private Integer disponibilidad;
     private String comision;
     private Set<LineaFactura> lineaFacturas = new HashSet<LineaFactura>(0);

    public Servicio() {
    }

	
    public Servicio(ServicioId id, Proveedor proveedor) {
        this.id = id;
        this.proveedor = proveedor;
    }
    public Servicio(ServicioId id, Proveedor proveedor, String nombre, Float costo, Integer disponibilidad, String comision, Set<LineaFactura> lineaFacturas) {
       this.id = id;
       this.proveedor = proveedor;
       this.nombre = nombre;
       this.costo = costo;
       this.disponibilidad = disponibilidad;
       this.comision = comision;
       this.lineaFacturas = lineaFacturas;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idServicio", column=@Column(name="idServicio", nullable=false) ), 
        @AttributeOverride(name="proveedorIdProveedor", column=@Column(name="Proveedor_idProveedor", nullable=false) ) } )
    public ServicioId getId() {
        return this.id;
    }
    
    public void setId(ServicioId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Proveedor_idProveedor", nullable=false, insertable=false, updatable=false)
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="costo", precision=12, scale=0)
    public Float getCosto() {
        return this.costo;
    }
    
    public void setCosto(Float costo) {
        this.costo = costo;
    }
    
    @Column(name="disponibilidad")
    public Integer getDisponibilidad() {
        return this.disponibilidad;
    }
    
    public void setDisponibilidad(Integer disponibilidad) {
        this.disponibilidad = disponibilidad;
    }
    
    @Column(name="comision", length=45)
    public String getComision() {
        return this.comision;
    }
    
    public void setComision(String comision) {
        this.comision = comision;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="servicio")
    public Set<LineaFactura> getLineaFacturas() {
        return this.lineaFacturas;
    }
    
    public void setLineaFacturas(Set<LineaFactura> lineaFacturas) {
        this.lineaFacturas = lineaFacturas;
    }




}


