package agencia.entity;
// Generated 14/06/2011 00:41:34 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Servicio generated by hbm2java
 */
public class Servicio  implements java.io.Serializable {


     private ServicioId id;
     private Proveedor proveedor;
     private String nombre;
     private Float costo;
     private Integer disponibilidad;
     private String comision;
     private Set<LineaFactura> lineaFacturas = new HashSet<LineaFactura>(0);

    public Servicio() {
    }

	
    public Servicio(ServicioId id, Proveedor proveedor) {
        this.id = id;
        this.proveedor = proveedor;
    }
    public Servicio(ServicioId id, Proveedor proveedor, String nombre, Float costo, Integer disponibilidad, String comision, Set<LineaFactura> lineaFacturas) {
       this.id = id;
       this.proveedor = proveedor;
       this.nombre = nombre;
       this.costo = costo;
       this.disponibilidad = disponibilidad;
       this.comision = comision;
       this.lineaFacturas = lineaFacturas;
    }
   
    public ServicioId getId() {
        return this.id;
    }
    
    public void setId(ServicioId id) {
        this.id = id;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Float getCosto() {
        return this.costo;
    }
    
    public void setCosto(Float costo) {
        this.costo = costo;
    }
    public Integer getDisponibilidad() {
        return this.disponibilidad;
    }
    
    public void setDisponibilidad(Integer disponibilidad) {
        this.disponibilidad = disponibilidad;
    }
    public String getComision() {
        return this.comision;
    }
    
    public void setComision(String comision) {
        this.comision = comision;
    }
    public Set<LineaFactura> getLineaFacturas() {
        return this.lineaFacturas;
    }
    
    public void setLineaFacturas(Set<LineaFactura> lineaFacturas) {
        this.lineaFacturas = lineaFacturas;
    }




}


